"""Initial schema with multi-niche support

Revision ID: fd3400259748
Revises: 
Create Date: 2026-02-08 22:18:23.238657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fd3400259748'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('price_per_hour', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_project_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_service_type'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('message_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_service_type'), 'knowledge_base', ['service_type'], unique=False)
    op.create_index(op.f('ix_knowledge_base_project_id'), 'knowledge_base', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.drop_table('healers')
    # ### end Alembic commands ###
