"""add_role_column_to_specialists

Revision ID: cf81f2948b29
Revises: 20250131100000
Create Date: 2026-02-03 08:35:56.337363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf81f2948b29'
down_revision: Union[str, None] = '20250131100000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('specialists', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'healer_nexus'"),
               existing_nullable=False)
    op.alter_column('specialists', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'healer_nexus'"),
               existing_nullable=False)
    op.alter_column('messages', 'project_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'healer_nexus'"),
               existing_nullable=False)
    # ### end Alembic commands ###
