"""Type stubs for asyncpg (if library doesn't provide types)."""
from typing import Any, Optional

class Connection:
    def is_closed(self) -> bool: ...
    async def execute(self, query: str, *args: Any) -> str: ...
    async def fetchval(self, query: str, *args: Any) -> Any: ...
    async def close(self) -> None: ...
    async def add_listener(self, channel: str, callback: Any) -> None: ...
    def get_server_version(self) -> tuple[int, int, int]: ...

class PostgresError(Exception): ...

async def connect(dsn: str, *, timeout: float = ..., command_timeout: float = ...) -> Connection: ...